name:                aoc22-haskell
version:             0.1.0.0

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- split
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  aoc22-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc22-haskell

tests:
  aoc22-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc22-haskell
    - hspec

benchmarks:
  aoc22-haskell-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
      - -with-rtsopts=-A32m
    dependencies:
      - aoc22-haskell
      - tasty-bench
      - deepseq

  aoc22-haskell-prof:
    main:                Prof.hs
    source-dirs:         prof
    ghc-options:
      - -with-rtsopts=-A32m
    dependencies:
      - aoc22-haskell
